name       : alsa-plugins
version    : 1.1.4
release    : 11
source     :
    - ftp://ftp.alsa-project.org/pub/plugins/alsa-plugins-1.1.4.tar.bz2 : 530d1c3bdaeb058f2a03607a33b9e16ee5369bfd30a96bc09bd2c69b4ddd1a8a
license    :
    - LGPL-2.1
    - GPL-2.0
component  : multimedia.audio
summary    : Plugins for various sound servers
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig32(alsa)
    - pkgconfig(speex)
    - pkgconfig32(speex)
    - pkgconfig(libpulse)
    - pkgconfig32(libpulse)
emul32     : yes
description: |
    Plugins to enable various sound servers
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
