name       : alsa-plugins
version    : 1.2.2
release    : 20
source     :
    - ftp://ftp.alsa-project.org/pub/plugins/alsa-plugins-1.2.2.tar.bz2 : 1c0f06450c928d711719686c9dbece2d480184f36fab11b8f0534cb7b41e337d
license    :
    - LGPL-2.1-or-later
    - GPL-2.0-or-later
component  : multimedia.audio
emul32     : yes
summary    : Plugins for various sound servers
description: |
    Plugins to enable various sound servers
builddeps  :
    - pkgconfig32(alsa)
    - pkgconfig32(jack)
    - pkgconfig32(libpulse)
    - pkgconfig32(samplerate)
    - pkgconfig32(speex)
setup      : |
    %configure --disable-static --with-alsalconfdir=/usr/share/alsa/conf.d/
build      : |
    %make
install    : |
    %make_install
