name        : alsa-plugins
version     : 1.0.27
release     : 5
source      :
    - ftp://ftp.alsa-project.org/pub/plugins/alsa-plugins-1.0.27.tar.bz2 : 0bbd0c37c2dd7baf16363afb2e58169ffb0f9c0a70031b3b6235594630f3ab35
homepage    : http://www.alsa-project.org/main/index.php/Main_Page
license     :
    - LGPL-2.1
    - GPL-2.0
summary     : Plugins for various sound servers
builddeps   :
    - pkgconfig(alsa)
    - pkgconfig(speex)
    - pkgconfig(libpulse)
description : |
    Plugins to enable various sound servers
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
