name       : alsa-plugins
version    : 1.1.5
release    : 13
source     :
    - ftp://ftp.alsa-project.org/pub/plugins/alsa-plugins-1.1.5.tar.bz2 : 797da5f8f53379fbea28817bc466de16affd2c07849e84f1af8d5e22f7bb7f1c
license    :
    - LGPL-2.1
    - GPL-2.0
component  : multimedia.audio
emul32     : yes
summary    : Plugins for various sound servers
description: |
    Plugins to enable various sound servers
builddeps  :
    - pkgconfig32(alsa)
    - pkgconfig32(speex)
    - pkgconfig32(libpulse)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
