name       : alsa-plugins
version    : 1.1.8
release    : 14
source     :
    - ftp://ftp.alsa-project.org/pub/plugins/alsa-plugins-1.1.8.tar.bz2 : 7f77df171685ccec918268477623a39db4d9f32d5dc5e76874ef2467a2405994
license    :
    - LGPL-2.1-or-later
    - GPL-2.0-or-later
component  : multimedia.audio
emul32     : yes
summary    : Plugins for various sound servers
description: |
    Plugins to enable various sound servers
builddeps  :
    - pkgconfig32(alsa)
    - pkgconfig32(jack)
    - pkgconfig32(libpulse)
    - pkgconfig32(samplerate)
    - pkgconfig32(speex)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
