name        : alsa-plugins
version     : 1.1.1
release     : 6
source     :
    - ftp://ftp.alsa-project.org/pub/plugins/alsa-plugins-1.1.1.tar.bz2 : 8ea4d1e082c36528a896a2581e5eb62d4dc2683238e353050d0d624e65f901f1
license     :
    - LGPL-2.1
    - GPL-2.0
summary     : Plugins for various sound servers
builddeps   :
    - pkgconfig(alsa)
    - pkgconfig(speex)
    - pkgconfig(libpulse)
description : |
    Plugins to enable various sound servers
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
