name       : alsa-plugins
version    : 1.1.1
release    : 7
source     :
    - ftp://ftp.alsa-project.org/pub/plugins/alsa-plugins-1.1.1.tar.bz2 : 8ea4d1e082c36528a896a2581e5eb62d4dc2683238e353050d0d624e65f901f1
license    :
    - LGPL-2.1
    - GPL-2.0
summary    : Plugins for various sound servers
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig32(alsa)
    - pkgconfig(speex)
    - pkgconfig32(speex)
    - pkgconfig(libpulse)
    - pkgconfig32(libpulse)
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
description: |
    Plugins to enable various sound servers
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
