name       : alsa-plugins
version    : 1.1.9
release    : 15
source     :
    - ftp://ftp.alsa-project.org/pub/plugins/alsa-plugins-1.1.9.tar.bz2 : 161772303da521abbbf1d91f63b470c4791392d5728f2192a42d71292078f907
license    :
    - LGPL-2.1-or-later
    - GPL-2.0-or-later
component  : multimedia.audio
emul32     : yes
summary    : Plugins for various sound servers
description: |
    Plugins to enable various sound servers
builddeps  :
    - pkgconfig32(alsa)
    - pkgconfig32(jack)
    - pkgconfig32(libpulse)
    - pkgconfig32(samplerate)
    - pkgconfig32(speex)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
